#!/usr/bin/env python3

from os.path import join

from wiki_c.auto_correction import BaseDetection, FormatOperation, walk

DIR_URL_DESTINATION = 'dokuwiki_result'

class DoubleDashFormatOperation(FormatOperation):
    prefix_summary = "correction tirets doubles"

    def _replace(self, doc, detected_lines):
        for line in detected_lines:
            doc = doc.replace("''--", "''​%%--%%")
        return doc


class DoubleDashDetection(BaseDetection):
    pattern = "''-- rather than ''​%%--%%"

    def _extract(self, line):
        return {
            'before': "''--",
            'after': "''​%%--%%"
        }


if __name__ == '__main__':
    print('Enter login :')
    login = input()
    print('Enter password :')
    password = input()

    walk(
        login, password,
        DIR_URL_DESTINATION,
        DoubleDashDetection,
        DoubleDashFormatOperation
    )
