#!/usr/bin/env python3

from wiki_c.auto_correction import BaseDetection, FormatOperation, walk, authenticate

DIR_URL_DESTINATION = 'url_result'


class HttpToHttpsFormatOperation(FormatOperation):
    prefix_summary = "Passage de http à https sur les liens externes"

    def _replace(self, doc, detected_lines):
        for line in detected_lines:
            doc = doc.replace(line['http'], line['https'])
        return doc


class HttpDetection(BaseDetection):
    pattern = "HTTP redirect to HTTPS"

    def _extract(self, line):
        return {
            'http': line[line.find('http://'):line.find(' => ')],
            'https': line[line.find('https://'):]
        }


if __name__ == '__main__':
    login, password = authenticate()

    detection = HttpDetection()
    d = detection.get('', '', DIR_URL_DESTINATION)
    datas = [ d ]
    print(datas)
    exit(0)
    replace_page(login, password, datas, HttpToHttpsFormatOperation)
    #walk(
    #    login, password,
    #    DIR_URL_DESTINATION,
    #    HttpDetection,
    #    HttpToHttpsFormatOperation
    #)
