#!/usr/bin/env python3

from wiki_c.auto_correction import BaseDetection, FormatOperation, walk, replace_page, authenticate

DIR_URL_DESTINATION = 'grammar_result'


class SpacesFormatOperation(FormatOperation):
    prefix_summary = "Suppression des espaces surnuméraires"

    def _replace(self, doc, detected_lines):
        for line in detected_lines:
            doc = doc.replace(line['before'], line['after'])
        return doc


class SpacesDetection(BaseDetection):
    pattern = "Espace(s) surnuméraire(s) à supprimer. => "

    def _extract(self, line):      
        before = line.strip()
        after = before.replace('    ', ' ').replace('   ', ' ').replace('  ', ' ')

        return {
            'before': before,
            'after': after
        }


if __name__ == '__main__':
    login, password = authenticate()

    #detection = SpacesDetection()
    #d = detection.get(DIR_URL_DESTINATION, 'zram.txt', DIR_URL_DESTINATION)
    #datas = [ d ]
    #replace_page(login, password, datas, SpacesFormatOperation)

    walk(
        login, password,
        DIR_URL_DESTINATION,
        SpacesDetection,
        SpacesFormatOperation
    )
