#!/usr/bin/env python3

import os
from os.path import join
import fnmatch

def walk(_dir):
    words = {}
    for root, _dir, files in os.walk(_dir):
        for _file in fnmatch.filter(files, '*'):
            if _file == 'index.toml':
                continue
            file_path = join(root, _file)

            for line in open(file_path):
                if line.strip() == "":
                    continue

                word = line[line.find(' '):line.find(' [[')]
                if word in words.keys():
                    words[word] = words[word] + 1
                    continue
                words[word] = 1
    return words


if __name__ == '__main__':
    content = '# Statistiques\n\n'

    content += '## Mots interdits :\n\n'
    words = walk('not_allowed_result')
    for w in sorted(words, key=words.get, reverse=False):
        content += f'{w} : {words[w]}\n'

    with open('stats_recurrent_not_allowed.md', 'w') as f:
        f.write(content)
