#!/usr/bin/env python3

import os
from os.path import join
import fnmatch

def walk(_dir):
    words = {}
    for root, _dir, files in os.walk(_dir):
        for _file in fnmatch.filter(files, '*'):
            if _file == 'index.toml':
                continue
            file_path = join(root, _file)
            pattern = 'Mot inconnu :'
            for line in open(file_path):
                if not pattern in line:
                    continue
                if line.strip() == "":
                    continue

                new_line = line[line.find(pattern) + len(pattern):]
                word = new_line[+1:new_line.find(' [[')]
                if word in words.keys():
                    words[word] = words[word] + 1
                    continue
                words[word] = 1
    return words


if __name__ == '__main__':
    content = '# Statistiques\n\n'

    content += '## Soucis de grammaire :\n\n'
    words = walk('grammar_result')
    for w in sorted(words, key=words.get, reverse=False):
        content += f'{w} : {words[w]}\n'

    with open('stats_mots_recurrents.md', 'w') as f:
        f.write(content)
