#!/usr/bin/env python3

import os
from os.path import join
import fnmatch

def walk(_dir):
    inc_file = 0
    nb_lines = 0
    for root, _dir, files in os.walk(_dir):
        for _file in fnmatch.filter(files, '*'):
            if _file == 'index.toml':
                continue
            file_path = join(root, _file)
            inc_file += 1
            _nb_lines = sum(1 for line in open(file_path))
            if _nb_lines == 0:
                print(file_path)
                os.remove(file_path)
            nb_lines += _nb_lines
    return (inc_file, nb_lines)


if __name__ == '__main__':
    content = '# Statistiques\n\n'

    content += '## Urls non conformes :\n\n'
    result = walk('url_result')
    content += f'  * Nombres de fichiers : {result[0]}\n'
    content += f'  * Nombres de remontées : {result[1]}\n\n'

    content += '## Soucis de grammaire :\n\n'
    result = walk('grammar_result')
    content += f'  * Nombres de fichiers : {result[0]}\n'
    content += f'  * Nombres de remontées : {result[1]}\n\n'

    content += '## Soucis de balises Dokuwiki :\n\n'
    result = walk('dokuwiki_result')
    content += f'  * Nombres de fichiers : {result[0]}\n'
    content += f'  * Nombres de remontées : {result[1]}\n\n'

    with open('stats.md', 'w') as f:
        f.write(content)
