#!/usr/bin/env python3

import os
from pathlib import Path
from os.path import join
import asyncio
import fnmatch

import aiohttp
from scrapy.selector import Selector

DIR_URL_DESTINATION = 'url_result'


def replace(doc, https_lines):
    for line in https_lines:
        doc = doc.replace(line['http'], line['https'])
    return doc


async def update(login, password, url, https_lines):
    url = f'{url}?do=edit'
    async with aiohttp.ClientSession() as session:
        connection_payload = {
            'id': 'accueil',
            'do': 'login',
            'u': login,
            'p': password
        }
        async with session.post('https://doc.ubuntu-fr.org/accueil?do=login', data=connection_payload):
            pass

        async with session.get(url) as r:
            page = await r.text()

        page_sel = Selector(text=page)
        dokuwiki = page_sel.css('#wiki__text::text').get()
        sectok = page_sel.xpath('//input[@name="sectok"]').attrib['value']
        date = page_sel.xpath('//input[@name="date"]').attrib['value']
        changecheck = page_sel.xpath('//input[@name="changecheck"]').attrib['value']

        payload = {
            'sectok': sectok,
            'date': date,
            'changecheck': changecheck,
            'summary': 'passage de http à https sur les liens externes (détecté et corrigé via le bot wiki-corrector (https://forum.ubuntu-fr.org/viewtopic.php?id=2067892)',
            'do[save]': '',
            'wikitext': replace(dokuwiki, https_lines)
        }

        async with session.post(url, data=payload):
            pass


def extract_link(line):
    return {
        'http': line[line.find('http://'):line.find(' => ')],
        'https': line[line.find('https://'):]
    }


def replace_page(login, password, root, _file):
    content = Path(join(root, _file)).read_text(encoding='UTF-8')
    has_https = 'HTTP redirect to HTTPS'
    if not has_https in content:
        return
    lines = content.split('\n')
    https_lines = [extract_link(line) for line in lines if has_https in line]

    url = join(
        'https://doc.ubuntu-fr.org/',
        root.replace(f'{DIR_URL_DESTINATION}', ''),
        _file.replace('.txt', '')
    )
    asyncio.run(update(login, password, url, https_lines))
    lines = [line for line in lines if not has_https in line]
    
    # update file
    with open(join(root, _file), 'w') as f:
        f.write('\n'.join(lines))

def walk(login, password):
    for root, _dir, files in os.walk(DIR_URL_DESTINATION):
        for _file in fnmatch.filter(files, '*'):
            print('Editer "%s" ?' % join(root, _file.replace('.txt', '')))
            input()
            replace_page(login, password, root, _file)


if __name__ == '__main__':
    print('Enter login :')
    login = input()
    print('Enter password :')
    password = input()

    #replace_page(login, password, DIR_URL_DESTINATION, 'abiword.txt')
    walk(login, password)
